trigger:
- main  # Rama principal que activará la pipeline

pool:
  name: default  

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13.1'  # Especifica la versión de Python (ejemplo: 3.9)

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    python -m unittest discover
  displayName: 'Instalar dependencias y ejecutar pruebas'
