# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main  # o la rama que quieras usar como trigger

pool:
  name: Default  # Este es el nombre por defecto del pool de agentes self-hosted. Ajusta según tu configuración

variables:
  - group: sql-credentials  # Grupo de variables para credenciales seguras
  - name: sourceFolder
    value: '$(System.DefaultWorkingDirectory)/SQL'  # Carpeta donde estarán tus scripts SQL
  - name: targetFolder
    value: '$(Build.ArtifactStagingDirectory)/SQL_Versioned'

stages:
- stage: Deploy
  jobs:
  - job: ProcessAndExecuteSQL
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - task: PowerShell@2
      displayName: 'Install Required Python Packages'
      inputs:
        targetType: 'inline'
        script: |
          python -m pip install --upgrade pip
          pip install pyodbc
          pip install pywin32

    - task: PowerShell@2
      displayName: 'Create Version Folder and Copy Files'
      inputs:
        targetType: 'inline'
        script: |
          # Crear carpeta de destino con formato de versión
          $date = Get-Date -Format "yyyyMMdd"
          $buildId = "$(Build.BuildId)".PadLeft(3, '0')
          $version = "1.0.0"  # Puedes modificar esto según tu lógica de versionado
          $folderName = "$buildId - $date - TK-$(System.TeamProject) - V$version"
          $targetPath = Join-Path "$(targetFolder)" $folderName
          
          # Copiar archivos SQL modificados
          New-Item -ItemType Directory -Path $targetPath -Force
          Get-ChildItem -Path "$(sourceFolder)" -Filter *.sql -Recurse | 
            Where-Object { $_.LastWriteTime -gt (Get-Date).AddMinutes(-$(timeWindow)) } |
            ForEach-Object {
              $relativePath = $_.FullName.Substring("$(sourceFolder)".Length)
              $destination = Join-Path $targetPath $relativePath
              New-Item -ItemType Directory -Path (Split-Path $destination) -Force
              Copy-Item $_.FullName -Destination $destination -Force
            }

    - task: PowerShell@2
      displayName: 'Execute SQL Scripts'
      inputs:
        targetType: 'inline'
        script: |
          # Configurar la cadena de conexión
          $server = "$(sqlServerName)"
          $database = "$(databaseName)"
          $username = "$(sqlUsername)"
          $password = "$(sqlPassword)"
          
          # Obtener todos los archivos SQL en orden
          $sqlFiles = Get-ChildItem -Path "$(targetFolder)" -Filter *.sql -Recurse | Sort-Object FullName
          
          foreach ($file in $sqlFiles) {
              Write-Host "Executing SQL file: $($file.FullName)"
              
              # Ejecutar el script SQL usando SQLCMD
              $output = sqlcmd -S $server -d $database -U $username -P $password -i $file.FullName -b
              
              if ($LASTEXITCODE -ne 0) {
                  Write-Error "Error executing SQL file: $($file.FullName)"
                  Write-Error $output
                  exit 1
              }
              
              Write-Host "Successfully executed: $($file.FullName)"
          }

    - task: PowerShell@2
      displayName: 'Send Notification Email'
      condition: always()
      inputs:
        targetType: 'inline'
        script: |
          $outlook = New-Object -ComObject Outlook.Application
          $mail = $outlook.CreateItem(0)
          $mail.To = "adbella@hk.com.ar"
          $mail.Subject = "Resultado de implementación: $([System.Environment]::GetEnvironmentVariable('AGENT_JOBSTATUS'))"
          $mail.HTMLBody = @"
          <html>
              <body>
                  <h2>Notificación de Implementación</h2>
                  <p><strong>Estado: </strong>$([System.Environment]::GetEnvironmentVariable('AGENT_JOBSTATUS'))</p>
                  <p><strong>Build:</strong> $(Build.BuildNumber)</p>
                  <p><strong>Fecha:</strong> $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</p>
              </body>
          </html>
          "@
          $mail.Send()

    - task: PublishBuildArtifacts@1
      displayName: 'Publish SQL Scripts'
      inputs:
        PathtoPublish: '$(targetFolder)'
        ArtifactName: 'SQL_Scripts'
        publishLocation: 'Container'